name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\activate
        pip install -r requirements.txt
        pip install pytest  # Install pytest

    - name: Run tests
      run: |
        .\venv\Scripts\activate
        pytest

    # Add MLflow step to save artifacts
    - name: Save MLflow artifacts
      run: |
        .\venv\Scripts\activate
        mlflow ui &
      env:
        MLFLOW_TRACKING_URI: 'http://127.0.0.1:5000'
        MLFLOW_EXPERIMENT_NAME: 'MLProjectExperiment'
